### ISSUE TITLE
gtk4 feedback

### ISSUE THREAD

**Issue by mckaygerhard** [cat-in-136/FlatSurfacesTheme#8] opened 2023-12-28 01:33 UTC
noted the new gtk4 branch also.. i will report feedback too

- [x] big space between elements of menues in gtk4 as in #7 7d41c91544a8a320893fc35f0a7065b746328133
- [x] some big spaces in styling of some widget/parts on gtk4 engine  7d41c91544a8a320893fc35f0a7065b746328133

### big space between elements of menues in gtk4

menues in gtk2 are great and elements are compact and concise, no waste of space..(right side of the picture) ideal for high or reduced screens.. 

but not for gtk3/gtk4, there are too much space beetween elements (left side of the picture)

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/69f4f7ec-5ac6-4e69-bee2-f60fb8ba0cab)

### some big spaces in styling of some widget/parts on gtk4 engine 

but some parts are too big, here border of client side decorations and also chromium/brave download bar, seems stupid effects of client-crap-side decorations in some gpus are confused.. i am sure is gtk4 styling cos if you use default one it does not happened.. 

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/e4c3feef-c761-4e08-8a25-d2631bd700b0)

by example tabs are great! no waste of space, gtk4 rendering seems good, mpv looks finally with no waste of space (stupid developers liked to waste space in anything? what the hell are thinking, apps are not web things)

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/6ac11b62-eb38-4d6d-bc32-33401369848c)

**Comment by cat-in-136** [comment] 2023-12-28 11:47
Duplicate of #7

**Comment by mckaygerhard** [comment] 2023-12-28 13:35
not per se duplication.. this is only for gtk4 branch

**Comment by mckaygerhard** [comment] 2023-12-29 20:09
ok tested now.. and everything works well. but in mysqlworkbench something rare happened and i cannot find why:

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/cfa029f2-eb26-4096-88b2-ca42e27f5ff3)

**Comment by mckaygerhard** [comment] 2024-02-06 13:23
Hi @cat-in-136  i tested again lasted gtk4 branch changes and sorry that my response are not good news.. seems under lxde it works but under mate does not (at least for winbuntu 20 LTS) for the black flavour.. 

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/e7b5ae5e-2588-4886-bed6-ea8e79bda166)

tonight i will test againa but under others appropiate distros.. sorry for bad news

i assume the changes were those:

* [version v0.8.1](https://github.com/cat-in-136/FlatSurfacesTheme/commit/8a87ccffe6de34e1f4de26e01a9f3ad23bd829b5)
[cat-in-136](https://github.com/cat-in-136/FlatSurfacesTheme/commits?author=cat-in-136)
* [set min-height of headerbar to 24px](https://github.com/cat-in-136/FlatSurfacesTheme/commit/1943bb36b99da50f6b36ac22000c0d8705e46a34)
[cat-in-136](https://github.com/cat-in-136/FlatSurfacesTheme/commits?author=cat-in-136)
* [fix infobar text color and introduce levelbar color](https://github.com/cat-in-136/FlatSurfacesTheme/commit/7c2f73bd91f135cce512eb2748ac5eecaf74f083)
[cat-in-136](https://github.com/cat-in-136/FlatSurfacesTheme/commits?author=cat-in-136)
* [add box-shadow to popover](https://github.com/cat-in-136/FlatSurfacesTheme/commit/26174c835343fd9758294b55f9b5600aca4e8e1d)
[cat-in-136](https://github.com/cat-in-136/FlatSurfacesTheme/commits?author=cat-in-136)

**Comment by cat-in-136** [comment] 2024-02-06 16:00
w.r.t. I could not reproduced your issue of mysqlworkbench. In addition, I could not found the port of GTK4. mysql-workbench-community-8.0.36 (latest version of community edition) is GTK3 app.

**Closed as completed** 2024-02-06 16:20 UTC
Labels: duplicate
